---
- name: Install yum-cron
  package: name=yum-cron state=present
  become: yes

- name: Install yum-cron config
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    state: present
    backrefs: yes
    regexp: '^apply_updates'
    line: 'apply_updates = yes'
  become: yes
  notify:
    - restart yum-cron
